config/routes.rb
Rails.application.routes.draw do
  resources :images, param: :uuid, only: [:create, :show] do
    post "flag", on: :member
    post "add_comment", on: :member
  end

  root to: "images#home"
end

app/models/comment.rb
require "awesome_nested_set"

class Comment < ActiveRecord::Base
  acts_as_nested_set scope: [:commentable_id, :commentable_type]

  validates :body, presence: true
  # NOTE: in this particular app, we want to allow for anonymous comments
  #validates :commentator, presence: true
  belongs_to :commentable, polymorphic: true
  belongs_to :commentator, polymorphic: true

  # Maximum depth can set how many children comments are permitted.
  MAX_DEPTH = 4

  after_save :bind_to_nth_parent

  class << self
    def build_from(commentable, commentator, comment_body)
      new \
      commentable: commentable,
      body: comment_body,
      commentator: commentator
    end

    def build_from_as_child_of(commentable, commentator, comment_body, parent_comment_id)
      new \
      commentable: commentable,
      body:  comment_body,
      commentator: commentator,
      parent_id: parent_comment_id
    end


    def find_commentable(commentable_str, commentable_id)
      commentable_str.constantize.find(commentable_id)
    end
  end

  # Scope to find all comments assigned to all commentable types for a given user.
  scope :find_comments_by_commentator, lambda { |commentator|
    where(commentator_id: commentator.id).order(created_at: :desc)
  }

  # Scope to find all comments for commentable class name and commentable id.
  scope :find_comments_for_commentable, lambda { |type, id|
    where(commentable_type: type.to_s, commentable_id: id)
        .order(created_at: :desc)
  }

  def has_children?
    children.any?
  end

  private
  def bind_to_nth_parent
    ancestors = self.ancestors
    unless ancestors.empty? || MAX_DEPTH == -1
      parent_comment = self.ancestors[MAX_DEPTH - 1] || self.ancestors.last
      self.move_to_child_of(parent_comment)
    end
  end
end

app/models/image.rb
require "acts_as_commentable_with_threading"

class Image < ActiveRecord::Base
  mount_uploader :image, ImageUploader
  validates :image, file_size: {less_than_or_equal_to: 20.megabytes}

  acts_as_commentable

  def hierarchical_comments
    BrianSpeak.translate( self.comment_threads ).as_json
  end

private

  # transforms an array of objects with "id" and "parent_id" into a tree
  def make_tree(array, pid=nil)
    array.select{ |n|
      n["parent_id"] == pid
    }.map{ |n|
      n.merge( children: make_tree( array, n["id"] ) )
    }
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/images_controller.rb
class ImagesController < ApplicationController
  skip_before_action :verify_authenticity_token
  before_action :load_comment_count
  
  def home
  end

  def show
    @image = Image.find_by!( uuid: params[:uuid] )
  end

  def create
    image = Image.new
    image.image = params[:image]
    image.uuid = SecureRandom.uuid
    image.save!

    respond_to do |format|
      format.js do
        render json: {link: image_url( image.uuid )}, status: :created
      end
      format.html do
        redirect_to image_url( image.uuid )
      end
    end
  end

  def flag
    image = Image.find_by!( uuid: params[:uuid] )
    image.flag_count = image.flag_count + 1
    image.save

    redirect_to image
  end

  def add_comment
    image = Image.find_by!( uuid: params[:uuid] )

    comment = Comment.create!(
      commentable: image,
      body: comment_params[:body],
      username: comment_params[:username],
      parent_id: comment_params[:parent_id],
      # FIXME: remove the below 2 lines when Jason updates the gem
      commentator_id: 0,
      commentator_type: ""
    )

    render json: { comment: BrianSpeak.as_brian_comment(comment) }, status: :created
  end

private

  def comment_params
    params.require( :comment ).permit( :body, :username, :parent_id )
  end


  def load_comment_count
    image = Image.find_by!( uuid: params[:uuid] )
    @comment_count = image.comment_threads.size
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/images/home.html.erb
<form enctype="multipart/form-data" action="/images" method="post">
  <%= tag(:input, :type => "hidden", :name => request_forgery_protection_token.to_s, :value => form_authenticity_token) %> 
  <input type="file" name="image" />
  <input type="submit" value="Create Image" />
</form>

app/views/images/show.html.erb
<script>
  window.comments = <%= raw @image.hierarchical_comments.to_json %>;
</script>
<nav class="navigation">
  <%= image_tag('skimg-logo.png', class: 'logo') %>
  <%= text_field_tag 'url', "#{request.host_with_port}/images/#{@image.uuid}" %>
  <div class="comment-info">
    <div><%= pluralize(@comment_count, 'comment') %></div>
    <a id="comment-message-box" href="#">Show Comments</a>
  </div>
</nav>
<div class="img-container">
  <% if @image.flag_count < 3 %>
      <img src="<%= @image.image.url %>">
      <div class="flag-container">
        <%= button_to "Flag Image as inappropriate", flag_image_path(@image.uuid), remote: true, class: 'btn btn-default' %>
      </div>
  <% else %>
      <h1>Image has been flagged as inappropriate and has been removed.</h1>
  <% end %>
</div>
<div class="mercury-blade container" id="app"></div>
<%= javascript_include_tag 'react-only', 'data-turbolinks-track' => true %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Mercuryblade</title>

  <meta charset="UTF-8"/>
  <link rel='stylesheet' href='https://fonts.googleapis.com/css?family=Open+Sans' type='text/css'>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css">
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.5.0/css/font-awesome.min.css">

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <%= yield %>

</body>
</html>